spring:
  profiles:
    active:test
---
spring:
  profiles:test
  application:
    name:test
server:
  port: 8011    

---
spring:
  profiles: dev
  application:
    name:dev
server:
  port: 8012      
---
spring:
  profiles: prod
  application:
    name:prod
server:
  port: 8013   