spring:
  profiles:
    active:test
---
server:
  port: 8011
spring:
  profiles: test
  application:
    name:  XZConfigClient

---
server:
  port: 8012
spring:
  profiles: dev
  application:
    name:  XZConfigClient
    
---
server:
  port: 8013
spring:
  profiles: prod
  application:
    name:  XZConfigClient