spring:
  profiles:
    active: test    
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: xztest
    username: root
    password: 123456
    connection-timeout: 10000
    template:
      mandatory: true
busi:
  ops: N
  
---
server:
  port: 8011
spring:
  profiles: test
  application:
    name:  XZConfigClient

---
server:
  port: 8014
spring:
  profiles: dev
  application:
    name:  XZConfigClient
    
---
server:
  port: 8013
spring:
  profiles: prod
  application:
    name:  XZConfigClient
